services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: expense-tracker-app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=expense_tracker
      - DB_USERNAME=postgres
      - DB_PASSWORD=secret

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=expense_tracker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/html
    depends_on:
      - app

volumes:
  pgdata: